/**
 
==============================================================================================================================================================================================================================================================================================================


*!                     INSTALACIÓN a través de NPM

1.Controlar que tenga instalada la ultima version de NodeJs o actualizarla.
2.Abrir CMD, actualizar npm (gestor de paquetes de NodeJs)
*?    npm install -g npm@latest
3.Borrar la Cache
*?    npm cache clean --force
4.Desactivar las auditorias para evitar fallos, temas de seguridad
*?    npm set audit false
5.Desinstalar En el caso que tenga versiones anteriores de Angular CLI, programa que genera  funcionalidades, servidor local, webpack para comprimir asets, generar builds, generar codigos, generar componentes, etc
*?    npm uninstall -g angular-cli
*?    npm unisntall -g @angular/cli
6.Borrar la cache nuevamente
*?    npm cache clean --force
7.Instalar la ultima version de Angular CLI
*?    npm install -g @angular/cli@latest
8. ir al directorio de nuestro proyecto donde quiera hacer uso de Angular
*?    ng new
(nos pide nombre del nuevo proyecto)
(opciones de css)
9. Arrancar el WEBPACK para que compile  y transcriba los ficheros y inicia un LIVE SERVE y "LIVE RELOAD" (angular cli con live reload RECARGA PANTALLA AUTOMATICAMENTE!)
* ?   ng serve

*todo            <<MANTENER EL "NG SERVE" CORRIENDO EN CMD para que funciones el live serve>>
*todo            <<MANTENER EL "NG SERVE" CORRIENDO EN CMD para que funciones el live serve>>
*todo            <<MANTENER EL "NG SERVE" CORRIENDO EN CMD para que funciones el live serve>>
*todo            <<MANTENER EL "NG SERVE" CORRIENDO EN CMD para que funciones el live serve>>



============================================================================================================================================================================================================================================================================================================== 

 */